name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: sudo apt-get install -y gcc make libsdl2-dev

    - name: List directory contents
      run: ls -la

    - name: Compile the project
      run: make  # Assumes you have a Makefile in your repository

    - name: List directory contents after build
      run: ls -la

    - name: Run the game
      run: ./my_game  # Ensure this is the correct executable nam
